### ISSUE TITLE
关于您的项目，有些问题请教，多谢

### ISSUE THREAD

**Issue by wangshoujunnew** [DannyLee1991/ai_qi#1]
在第一的
pip3 install -r requirements.txt中，一直缺少一些东西，个人现在在研究一些量化方面知识。期待您的回复

**Comment by DannyLee1991** [comment]
hi，感谢您的关注，方便把报错的信息贴上来吗？

**Comment by chenwq95** [comment]
Hi，我也碰到问题了，不太了解tudata是什么包，是否是您自己编写的呢
Collecting tudata==1.0 (from -r requirements.txt (line 46))
  Could not find a version that satisfies the requirement tudata==1.0 (from -r requirements.txt (line 46)) (from versions: )
No matching distribution found for tudata==1.0 (from -r requirements.txt (line 46))

**Comment by DannyLee1991** [comment]
不好意思，tudata==1.0这一行我已经删除，是一处错误的引入，你可以拉取一下最新代码。如果还有问题，请及时告诉我~

**Comment by chenwq95** [comment]
谢谢，已经成功运行了。不过还有一些包不在requirements.txt里，根据错误提示手动Install了
